"""revision #2

Revision ID: 2b5581546a75
Revises: d42a38bf91eb
Create Date: 2026-03-25 21:07:37.780618

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '2b5581546a75'
down_revision: Union[str, Sequence[str], None] = 'd42a38bf91eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
