"""add verification_jti and sent_at

Revision ID: 495a666f95b8
Revises: 307e7fe46903
Create Date: 2026-05-07 14:21:18.726074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495a666f95b8'
down_revision: Union[str, Sequence[str], None] = '307e7fe46903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_jti', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('verification_sent_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'verification_token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('users', 'verification_sent_at')
    op.drop_column('users', 'verification_jti')
    # ### end Alembic commands ###
