"""add_message_reply_fields

Revision ID: 6407ade23dda
Revises: af25278d05ab
Create Date: 2026-03-31 17:59:18.207699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6407ade23dda'
down_revision: Union[str, Sequence[str], None] = 'af25278d05ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('in_reply_to_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('in_reply_to_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['in_reply_to_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['in_reply_to_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'in_reply_to_user_id')
    op.drop_column('messages', 'in_reply_to_id')
    # ### end Alembic commands ###
