"""add_message_editing_pinning_and_attachments_fields

Revision ID: af25278d05ab
Revises: c76a3cea920e
Create Date: 2026-03-31 16:16:36.265237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af25278d05ab'
down_revision: Union[str, Sequence[str], None] = 'c76a3cea920e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edit_content', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('messages', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('pinned_by', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_name', sa.String(), nullable=True))
    
    # Update existing rows
    op.execute("UPDATE messages SET is_edited = false WHERE is_edited IS NULL")
    op.execute("UPDATE messages SET is_pinned = false WHERE is_pinned IS NULL")
    
    # Alter to NOT NULL after populating
    op.alter_column('messages', 'is_edited', existing_type=sa.Boolean(), nullable=False, server_default='false')
    op.alter_column('messages', 'is_pinned', existing_type=sa.Boolean(), nullable=False, server_default='false')
    
    op.create_foreign_key(None, 'messages', 'users', ['pinned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'file_type')
    op.drop_column('messages', 'file_url')
    op.drop_column('messages', 'pinned_by')
    op.drop_column('messages', 'pinned_at')
    op.drop_column('messages', 'is_pinned')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'edit_content')
    # ### end Alembic commands ###
