"""add_message_status_chat_last_message_and_user_online_fields

Revision ID: c76a3cea920e
Revises: bed10c4ca6de
Create Date: 2026-03-30 21:53:51.007219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76a3cea920e'
down_revision: Union[str, Sequence[str], None] = 'bed10c4ca6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'chats', 'messages', ['last_message_id'], ['id'])
    
    # Add message status columns with nullable=True first
    op.add_column('messages', sa.Column('is_delivered', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE messages SET is_delivered = true WHERE is_delivered IS NULL")
    op.execute("UPDATE messages SET is_read = false WHERE is_read IS NULL")
    op.execute("UPDATE messages SET is_deleted = false WHERE is_deleted IS NULL")
    
    # Alter columns to NOT NULL after populating
    op.alter_column('messages', 'is_delivered', existing_type=sa.Boolean(), nullable=False, server_default='true')
    op.alter_column('messages', 'is_read', existing_type=sa.Boolean(), nullable=False, server_default='false')
    op.alter_column('messages', 'is_deleted', existing_type=sa.Boolean(), nullable=False, server_default='false')
    
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    
    # Update existing users
    op.execute("UPDATE users SET is_online = false WHERE is_online IS NULL")
    op.alter_column('users', 'is_online', existing_type=sa.Boolean(), nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'is_online')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'is_read')
    op.drop_column('messages', 'is_delivered')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'last_message_at')
    op.drop_column('chats', 'last_message_id')
    # ### end Alembic commands ###
