"""add_group_chats_support

Revision ID: cfdfc9014ca8
Revises: 6407ade23dda
Create Date: 2026-04-05 23:49:13.992917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdfc9014ca8'
down_revision: Union[str, Sequence[str], None] = '6407ade23dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='memberrole', create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.add_column('chats', sa.Column('name', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('is_group', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('created_by', sa.Integer(), nullable=True))

    # Set is_group to False for existing chats
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE chats SET is_group = FALSE WHERE is_group IS NULL"))

    # Migrate existing 1-on-1 chats: populate chat_members from user_id_1 and user_id_2
    conn = op.get_bind()
    existing_chats = conn.execute(
        sa.text("SELECT id, user_id_1, user_id_2 FROM chats WHERE user_id_1 IS NOT NULL AND user_id_2 IS NOT NULL")
    ).fetchall()
    for chat_row in existing_chats:
        chat_id = chat_row[0]
        user_1 = chat_row[1]
        user_2 = chat_row[2]
        # Insert user_id_1 as member
        conn.execute(
            sa.text(
                "INSERT INTO chat_members (chat_id, user_id, role, joined_at, created_at, updated_at) "
                "VALUES (:chat_id, :user_id, 'member', NOW(), NOW(), NOW()) "
                "ON CONFLICT (chat_id, user_id) DO NOTHING"
            ),
            {"chat_id": chat_id, "user_id": user_1}
        )
        # Insert user_id_2 as member
        conn.execute(
            sa.text(
                "INSERT INTO chat_members (chat_id, user_id, role, joined_at, created_at, updated_at) "
                "VALUES (:chat_id, :user_id, 'member', NOW(), NOW(), NOW()) "
                "ON CONFLICT (chat_id, user_id) DO NOTHING"
            ),
            {"chat_id": chat_id, "user_id": user_2}
        )

    op.drop_constraint(op.f('chats_user_id_2_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_user_id_1_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['created_by'], ['id'])
    op.drop_column('chats', 'user_id_1')
    op.drop_column('chats', 'user_id_2')
    # Now make is_group NOT NULL since all existing rows have FALSE
    op.alter_column('chats', 'is_group', existing_type=sa.Boolean(), nullable=False, server_default='false')
    op.alter_column('messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('chats', sa.Column('user_id_2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('user_id_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_id_1_fkey'), 'chats', 'users', ['user_id_1'], ['id'])
    op.create_foreign_key(op.f('chats_user_id_2_fkey'), 'chats', 'users', ['user_id_2'], ['id'])
    op.drop_column('chats', 'created_by')
    op.drop_column('chats', 'is_group')
    op.drop_column('chats', 'name')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
