"""empty message

Revision ID: eeab2498aa50
Revises: 2440d8f05686
Create Date: 2026-04-30 04:33:37.890479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeab2498aa50'
down_revision: Union[str, Sequence[str], None] = '2440d8f05686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=False)
    op.drop_column('user_sessions', 'updated_at')
    # ### end Alembic commands ###
